Algoritmo "questão 2"
// Disciplina   : BANCO DE DADOS
// Professor   : Franchisquini
// Autor(a)    : Thiago Dond Ferreira Barbosa
// Data atual  : 27/09/2023
Var
valor_combul:inteiro
valorpago:real
tanque:real
Inicio
Escreva ("informe o valor do combustível:")
leia(valor_combul)
Escreva ("informe o valor pago:")
leia (valorpago)
tanque<-valor_combul/valorpago
Escreval (" você colocou no tanque a seguinte quantidade de litros:", tanque)

Fimalgoritmo