Algoritmo "questão 4"
// Disciplina   : BANCO DE DADOS
// Professor   : Franchisquini
// Autor(a)    : Thiago Dond Ferreira Barbosa
// Data atual  : 27/09/2023
Var
dia, mes: inteiro
totaldias: inteiro
Inicio
Escreva ("Dia atual:")
leia(dia)
Escreva ("Mês atual:")
leia(mes)
totaldias <- dia + (mes-1)*30
Escreval ("Passaram o total de", totaldias," dias desde o início do ano.")

Fimalgoritmo