Algoritmo "questão 5"
// Disciplina   : BANCO DE DADOS
// Professor   : Franchisquini
// Autor(a)    : Thiago Dond Ferreira Barbosa
// Data atual  : 27/09/2023
Var
p,m,g: inteiro
valor: inteiro
Inicio
Escreva ("Informe a quantidade de camisas Peqenas:")
leia(p)
Escreva ("Informe a quantidade de camisas Medias:")
leia(m)
Escreva ("Informe a quantidade de camisas Grandes:")
leia(g)
valor <- p*10 + m*12 + g*15
Escreval ("O valor arrecadado foi de: R$", valor)

Fimalgoritmo